### ISSUE TITLE
Y coordinate is not right 

### ISSUE THREAD

**Issue by pzy2253999075** [danielsnider/gps_goal#3]
I have used this stack in my robot_simulation,but I found a problem that  the  Y  coordinate   calculated from the  calc_goal() function is not fit  the ros coordinate.  why would be this?

**Comment by danielsnider** [comment]
What do you mean by "ros coordinate" and "not fit"?

Warm wishes,

**Comment by pzy2253999075** [comment]
Dear @danielsnider ,I am using gps_goal stack to navigate my robot, but I  don't kown how to transform the /map to WSG84 .could you give me the details on how to do this.I have seen your question and want to know how you fix this .https://answers.ros.org/question/261580/how-do-i-to-make-wgs84-frame-available/ . Thank you a lot

**Comment by danielsnider** [comment]
To transform from /map to WSG84 use [swri_transform_util](http://wiki.ros.org/swri_transform_util) node as I do in my [launch file](https://gist.github.com/danielsnider/a458938049f2d12784b8a5d664a12b72#file-mapviz-launch-L8).

> The swri_transform_util package contains utility functions and classes for transforming between coordinate frames.

An example of converting a point from /world (although you can do /map) to WSG84 using the `point_click_publisher` can be seen here: 
![image](https://user-images.githubusercontent.com/1737560/54825461-01bbf500-4c84-11e9-9c44-defbd1cc18b2.png)

But make sure you put a forward slash, it is important -- so "/wgs84" rather than "wgs84".

**Comment by pzy2253999075** [comment]
Dear @danielsnider ,I have a trace of confusion：what dose the code  actually do in the picture below
![image](https://user-images.githubusercontent.com/15712923/54874258-6f9e2300-4e22-11e9-8a58-b416c0c3700f.png),dose it do the work to bind my /map to /wsg84 by given the known gps point?yeah, I have tried your launch file.And I get the tf:
![image](https://user-images.githubusercontent.com/15712923/54874407-ac1f4e00-4e25-11e9-8491-5af524580454.png) But I see the transform between /map and /word is static . I don't think it is  a real tansform from /map to /wsg84 .  If I am wrong ,could you  explain it to me。Thank you  again

**Comment by danielsnider** [comment]
The latitude and longitude is the GPS location that will be associated with
(0,0) location in your ROS map coordinates. I'm not sure about the static
transformation. I'm no longer as familiar with it as I used to be! I miss
robots.


Warm wishes,
Daniel Snider ツ

**Comment by pzy2253999075** [comment]
@danielsnider   Ok,thank you for all your answers ，they help me a lot. I will close this issue.

**Comment by pzy2253999075** [comment]
@
