### ISSUE TITLE
Turn this into a ROS Service

### ISSUE THREAD

**Issue by vinnnyr** [danielsnider/gps_goal#5]
Was wondering if there would be any interest in turning this into a ros service instead of publisher /subscriber architectures as is now with the following proposed architecture. 

I currently have a fork of this working with the following changes

- GPS origin set by rosparam
- Custom Service Message to hold lat long and heading, that responds with the goal in PoseStamped form

Please let me know if there is interest in this, and I can open up a pull request.

**Comment by danielsnider** [comment]
Thanks very much. Seems like a nice contribution. I'll be in touch next
week when I have time to look at your branch.

**Comment by danielsnider** [comment]
For newcomers looking for a ROS Service implementation of `GPS_goal`, I recommend checking out @vinnnyr's branch: https://github.com/ros-agriculture/gps_goal_server/tree/make-server

Hi @vinnnyr, I'm sorry I still don't have the time to review the changes. In order to move forward with this pull request documentation and tests would be needed, as well as time for me to review the code. However it is not looking likely right now unless you have ample time.

All the best to you and @ros-agriculture!

**Comment by vinnnyr** [comment]
Sure, of course tests and documentation was being planned to be written . I wanted to get your thoughts on the concept at first. 

Seems like you might be pressed for time to review even if I were to make that happen, so for now I will keep it as is for our purposes, but will be open to working on this later If there is more interest :) 

Thanks @danielsnider !

**Comment by danielsnider** [comment]
That sounds perfect. Thanks for understanding.
